# This file contains all available configuration options
# with their default values.

# options for analysis running
run:
  # timeout for analysis, e.g. 30s, 5m, default is 1m
  timeout: 5m

  # exit code when at least one issue was found, default is 1
  issues-exit-code: 1

# output configuration options
output:
  # colored-line-number|line-number|json|tab|checkstyle, default is "colored-line-number"
  formats:
    - format: colored-line-number

  # print lines of code with issue, default is true
  print-issued-lines: true

  # print linter name in the end of issue text, default is true
  print-linter-name: true

linters:
  enable:
    # Sorted alphabetically.
    - errcheck
    - godot
    - gofmt
    - gci
    - gosimple
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - unparam
    - unused
    - copyloopvar
    - promlinter

linters-settings:
  errcheck:
    exclude-functions:
      - (github.com/go-kit/log.Logger).Log
      - fmt.Fprintln
      - fmt.Fprint
  misspell:
    locale: US
  gci:
    sections:
      - standard
      - prefix(github.com/thanos-io)
      - default
      - blank
      - dot
    skip-generated: false
    custom-order: true

issues:
  exclude-rules:
    # We don't check metrics naming in the tests.
    - path: _test\.go
      linters:
        - promlinter

  # which dirs to skip: they won't be analyzed;
  # can use regexp here: generated.*, regexp is applied on full path;
  # default value is empty list, but next dirs are always skipped independently
  # from this option's value:
  #     vendor$, third_party$, testdata$, examples$, Godeps$, builtin$
  exclude-dirs:
    - vendor
    - parser
