module _ // Auto generated by https://github.com/bwplotka/bingo. DO NOT EDIT

go 1.18

require github.com/efficientgo/tools/copyright v0.0.0-20220225185207-fe763185946b

require (
	github.com/alecthomas/template v0.0.0-20190718012654-fb15b899a751 // indirect
	github.com/alecthomas/units v0.0.0-20201120081800-1786d5ef83d4 // indirect
	github.com/efficientgo/tools/core v0.0.0-20210106193344-1108f4e7d16b // indirect
	github.com/golang/protobuf v1.4.3 // indirect
	github.com/pkg/errors v0.9.1 // indirect
	github.com/protoconfig/protoconfig/go v0.0.0-20210106192113-733758adefac // indirect
	google.golang.org/protobuf v1.25.0 // indirect
	gopkg.in/alecthomas/kingpin.v2 v2.2.6 // indirect
)
